# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  ğŸ‘‹ æ¬¢è¿ä½ ï¼Œæ–°æœ‹å‹ï¼å¦‚æœæ‚¨æ˜¯ä¸ºæœ¬ä¹¦å‹˜è¯¯ï¼Œè¯·è¯´æ˜å‡ºç°çš„å…·ä½“ä½ç½®ã€‚
  ğŸ‰ å¦‚æœæ‚¨åœ¨ï¼ˆæˆ–æœŸæœ›æ¥ï¼‰å—äº¬ï¼Œåˆæ°å·§åœ¨çœ‹å·¥ä½œæœºä¼šï¼Œå¯ä»¥æŠŠæ‚¨çš„ç®€å†å‘é€è‡³ i@sh.gg

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ğŸ’– æ¬¢è¿ä½ ï¼Œæ–°æœ‹å‹ï¼è¿™æ˜¯æ‚¨çš„ç¬¬ä¸€æ¬¡ä»£ç æäº¤ï¼Œè¯·è€å¿ƒç­‰å¾…åˆå¹¶å¤„ç†ã€‚
  ğŸ‰ å¦‚æœæ‚¨åœ¨ï¼ˆæˆ–æœŸæœ›æ¥ï¼‰å—äº¬ï¼Œåˆæ°å·§åœ¨çœ‹å·¥ä½œæœºä¼šï¼Œå¯ä»¥æŠŠæ‚¨çš„ç®€å†å‘é€è‡³ i@sh.gg
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  æ­å–œæ‚¨ï¼Œæ–°æœ‹å‹ï¼Œè¿™æ˜¯ç¬¬ä¸€æ¬¡åˆå¹¶æ‚¨çš„ä»£ç å‘¢! ğŸ‰ğŸ‰ğŸ‰
# It is recommend to include as many gifs and emojis as possiblec
